kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
  event:
    - push
    - cron

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: cenk1cenk2/openresty
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest

  - name: inform
    image: drillster/drone-email
    depends_on:
      - publish
    settings:
      host:
        from_secret: smtp_host
      port:
        from_secret: smtp_port
      username:
        from_secret: smtp_username
      password:
        from_secret: smtp_password
      from:
        from_secret: smtp_username
    when:
      status:
        - changed
        - failure
