stages:
  - docker
  - post

variables:
  DOCKER_IMAGE_NAME: cenk1cenk2/openresty

include:
  - project: devops/pipes
    file: /templates/v2/docker-build-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/docker-manifest-dockerhub.gitlab-ci.yml

  - project: devops/pipes
    file: /templates/v2/update-docker-hub-readme.gitlab-ci.yml

docker-build:
  stage: docker
  extends: .docker-build-dockerhub
  variables:
    RESTY_VERSION: '1.21.4.1'
    RESTY_IMAGE_TAG: '3.16'
    DOCKER_IMAGE_BUILD_ARGS: |-
      RESTY_VERSION={{ .RESTY_VERSION }},
      RESTY_IMAGE_TAG={{ .RESTY_IMAGE_TAG }}
  parallel:
    matrix:
      - DOCKERFILE_NAME: Dockerfile
        DOCKER_IMAGE_TAGS: latest-${GITLAB_CI_ARCH},${RESTY_IMAGE_TAG}-${RESTY_VERSION}-${GITLAB_CI_ARCH}
        DOCKER_MANIFEST_TARGET: latest
        GITLAB_CI_ARCH:
          - amd64
          - arm64
  only:
    refs:
      - schedules
      - main

docker-manifest:
  stage: post
  extends: .docker-manifest-dockerhub
  only:
    refs:
      - schedules
      - main

update-docker-hub-readme:
  stage: post
  extends: .update-docker-hub-readme
  variables:
    README_DESCRIPTION: |
      OpenResty image for personal use-case.
  only:
    refs:
      - schedules
      - main
